In [5]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
df=pd.read_csv('/content/kc_house_data.csv')

In [ ]:
df

id             date  bedrooms  bathrooms  sqft_living  \
0      7129300520  20141013T000000         3       1.00         1180   
1      6414100192  20141209T000000         3       2.25         2570   
2      5631500400  20150225T000000         2       1.00          770   
3      2487200875  20141209T000000         4       3.00         1960   
4      1954400510  20150218T000000         3       2.00         1680   
...           ...              ...       ...        ...          ...   
21608   263000018  20140521T000000         3       2.50         1530   
21609  6600060120  20150223T000000         4       2.50         2310   
21610  1523300141  20140623T000000         2       0.75         1020   
21611   291310100  20150116T000000         3       2.50         1600   
21612  1523300157  20141015T000000         2       0.75         1020   

       sqft_lot  floors  waterfront  view  condition  ...  sqft_above  \
0          5650     1.0           0     0          3  ...        1180   
1          7242     2.0           0     0          3  ...        2170   
2         10000     1.0           0     0          3  ...         770   
3          5000     1.0           0     0          5  ...        1050   
4          8080     1.0           0     0          3  ...        1680   
...         ...     ...         ...   ...        ...  ...         ...   
21608      1131     3.0           0     0          3  ...        1530   
21609      5813     2.0           0     0          3  ...        2310   
21610      1350     2.0           0     0          3  ...        1020   
21611      2388     2.0           0     0          3  ...        1600   
21612      1076     2.0           0     0          3  ...        1020   

       sqft_basement  yr_built  yr_renovated  zipcode      lat     long  \
0                  0      1955             0    98178  47.5112 -122.257   
1                400      1951          1991    98125  47.7210 -122.319   
2                  0      1933             0    98028  47.7379 -122.233   
3                910      1965             0    98136  47.5208 -122.393   
4                  0      1987             0    98074  47.6168 -122.045   
...              ...       ...           ...      ...      ...      ...   
21608              0      2009             0    98103  47.6993 -122.346   
21609              0      2014             0    98146  47.5107 -122.362   
21610              0      2009             0    98144  47.5944 -122.299   
21611              0      2004             0    98027  47.5345 -122.069   
21612              0      2008             0    98144  47.5941 -122.299   

       sqft_living15  sqft_lot15     price  
0               1340        5650  221900.0  
1               1690        7639  538000.0  
2               2720        8062  180000.0  
3               1360        5000  604000.0  
4               1800        7503  510000.0  
...              ...         ...       ...  
21608           1530        1509  360000.0  
21609           1830        7200  400000.0  
21610           1020        2007  402101.0  
21611           1410        1287  400000.0  
21612           1020        1357  325000.0  

[21613 rows x 21 columns]

In [ ]:
df.drop(['date'],axis=1 , inplace= True)

In [ ]:
df

id  bedrooms  bathrooms  sqft_living  sqft_lot  floors  \
0      7129300520         3       1.00         1180      5650     1.0   
1      6414100192         3       2.25         2570      7242     2.0   
2      5631500400         2       1.00          770     10000     1.0   
3      2487200875         4       3.00         1960      5000     1.0   
4      1954400510         3       2.00         1680      8080     1.0   
...           ...       ...        ...          ...       ...     ...   
21608   263000018         3       2.50         1530      1131     3.0   
21609  6600060120         4       2.50         2310      5813     2.0   
21610  1523300141         2       0.75         1020      1350     2.0   
21611   291310100         3       2.50         1600      2388     2.0   
21612  1523300157         2       0.75         1020      1076     2.0   

       waterfront  view  condition  grade  sqft_above  sqft_basement  \
0               0     0          3      7        1180              0   
1               0     0          3      7        2170            400   
2               0     0          3      6         770              0   
3               0     0          5      7        1050            910   
4               0     0          3      8        1680              0   
...           ...   ...        ...    ...         ...            ...   
21608           0     0          3      8        1530              0   
21609           0     0          3      8        2310              0   
21610           0     0          3      7        1020              0   
21611           0     0          3      8        1600              0   
21612           0     0          3      7        1020              0   

       yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0          1955             0    98178  47.5112 -122.257           1340   
1          1951          1991    98125  47.7210 -122.319           1690   
2          1933             0    98028  47.7379 -122.233           2720   
3          1965             0    98136  47.5208 -122.393           1360   
4          1987             0    98074  47.6168 -122.045           1800   
...         ...           ...      ...      ...      ...            ...   
21608      2009             0    98103  47.6993 -122.346           1530   
21609      2014             0    98146  47.5107 -122.362           1830   
21610      2009             0    98144  47.5944 -122.299           1020   
21611      2004             0    98027  47.5345 -122.069           1410   
21612      2008             0    98144  47.5941 -122.299           1020   

       sqft_lot15     price  
0            5650  221900.0  
1            7639  538000.0  
2            8062  180000.0  
3            5000  604000.0  
4            7503  510000.0  
...           ...       ...  
21608        1509  360000.0  
21609        7200  400000.0  
21610        2007  402101.0  
21611        1287  400000.0  
21612        1357  325000.0  

[21613 rows x 20 columns]

In [ ]:
df.corr()

id  bedrooms  bathrooms  sqft_living  sqft_lot    floors  \
id             1.000000  0.001286   0.005160    -0.012258 -0.132109  0.018525   
bedrooms       0.001286  1.000000   0.515884     0.576671  0.031703  0.175429   
bathrooms      0.005160  0.515884   1.000000     0.754665  0.087740  0.500653   
sqft_living   -0.012258  0.576671   0.754665     1.000000  0.172826  0.353949   
sqft_lot      -0.132109  0.031703   0.087740     0.172826  1.000000 -0.005201   
floors         0.018525  0.175429   0.500653     0.353949 -0.005201  1.000000   
waterfront    -0.002721 -0.006582   0.063744     0.103818  0.021604  0.023698   
view           0.011592  0.079532   0.187737     0.284611  0.074710  0.029444   
condition     -0.023783  0.028472  -0.124982    -0.058753 -0.008958 -0.263768   
grade          0.008130  0.356967   0.664983     0.762704  0.113621  0.458183   
sqft_above    -0.010842  0.477600   0.685342     0.876597  0.183512  0.523885   
sqft_basement -0.005151  0.303093   0.283770     0.435043  0.015286 -0.245705   
yr_built       0.021380  0.154178   0.506019     0.318049  0.053080  0.489319   
yr_renovated  -0.016907  0.018841   0.050739     0.055363  0.007644  0.006338   
zipcode       -0.008224 -0.152668  -0.203866    -0.199430 -0.129574 -0.059121   
lat           -0.001891 -0.008931   0.024573     0.052529 -0.085683  0.049614   
long           0.020799  0.129473   0.223042     0.240223  0.229521  0.125419   
sqft_living15 -0.002901  0.391638   0.568634     0.756420  0.144608  0.279885   
sqft_lot15    -0.138798  0.029244   0.087175     0.183286  0.718557 -0.011269   
price         -0.016797  0.308338   0.525134     0.702044  0.089655  0.256786   

               waterfront      view  condition     grade  sqft_above  \
id              -0.002721  0.011592  -0.023783  0.008130   -0.010842   
bedrooms        -0.006582  0.079532   0.028472  0.356967    0.477600   
bathrooms        0.063744  0.187737  -0.124982  0.664983    0.685342   
sqft_living      0.103818  0.284611  -0.058753  0.762704    0.876597   
sqft_lot         0.021604  0.074710  -0.008958  0.113621    0.183512   
floors           0.023698  0.029444  -0.263768  0.458183    0.523885   
waterfront       1.000000  0.401857   0.016653  0.082775    0.072075   
view             0.401857  1.000000   0.045990  0.251321    0.167649   
condition        0.016653  0.045990   1.000000 -0.144674   -0.158214   
grade            0.082775  0.251321  -0.144674  1.000000    0.755923   
sqft_above       0.072075  0.167649  -0.158214  0.755923    1.000000   
sqft_basement    0.080588  0.276947   0.174105  0.168392   -0.051943   
yr_built        -0.026161 -0.053440  -0.361417  0.446963    0.423898   
yr_renovated     0.092885  0.103917  -0.060618  0.014414    0.023285   
zipcode          0.030285  0.084827   0.003026 -0.184862   -0.261190   
lat             -0.014274  0.006157  -0.014941  0.114084   -0.000816   
long            -0.041910 -0.078400  -0.106500  0.198372    0.343803   
sqft_living15    0.086463  0.280439  -0.092824  0.713202    0.731870   
sqft_lot15       0.030703  0.072575  -0.003406  0.119248    0.194050   
price            0.266331  0.397346   0.036392  0.667463    0.605566   

               sqft_basement  yr_built  yr_renovated   zipcode       lat  \
id                 -0.005151  0.021380     -0.016907 -0.008224 -0.001891   
bedrooms            0.303093  0.154178      0.018841 -0.152668 -0.008931   
bathrooms           0.283770  0.506019      0.050739 -0.203866  0.024573   
sqft_living         0.435043  0.318049      0.055363 -0.199430  0.052529   
sqft_lot            0.015286  0.053080      0.007644 -0.129574 -0.085683   
floors             -0.245705  0.489319      0.006338 -0.059121  0.049614   
waterfront          0.080588 -0.026161      0.092885  0.030285 -0.014274   
view                0.276947 -0.053440      0.103917  0.084827  0.006157   
condition           0.174105 -0.361417     -0.060618  0.003026 -0.014941   
grade               0.168392  0.446963      0.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   id             21613 non-null  int64  
 1   bedrooms       21613 non-null  int64  
 2   bathrooms      21613 non-null  float64
 3   sqft_living    21613 non-null  int64  
 4   sqft_lot       21613 non-null  int64  
 5   floors         21613 non-null  float64
 6   waterfront     21613 non-null  int64  
 7   view           21613 non-null  int64  
 8   condition      21613 non-null  int64  
 9   grade          21613 non-null  int64  
 10  sqft_above     21613 non-null  int64  
 11  sqft_basement  21613 non-null  int64  
 12  yr_built       21613 non-null  int64  
 13  yr_renovated   21613 non-null  int64  
 14  zipcode        21613 non-null  int64  
 15  lat            21613 non-null  float64
 16  long           21613 non-null  float64
 17  sqft_living15  21613 non-null  int64  
 18  sqft_l

In [ ]:
df.isnull().sum()

id               0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
grade            0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
zipcode          0
lat              0
long             0
sqft_living15    0
sqft_lot15       0
price            0
dtype: int64

# Simple Linear regression

In [ ]:
X= df.iloc[:,9:10].values
X

array([[7],
       [7],
       [6],
       ...,
       [7],
       [8],
       [7]])

In [ ]:
y= df.iloc[:,-1].values
y

array([221900., 538000., 180000., ..., 402101., 400000., 325000.])

# Splitting Dataset into Training & Testing set

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

# Training Simple Linear Model on Training Set

In [ ]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression()

# Predicting the Test set result

In [ ]:
y_pred=regressor.predict(X_test)
y_pred

array([ 404310.6017, 1454122.8442,  404310.6017, ...,  404310.6017,
        194348.1532,  404310.6017])

In [ ]:
y_test

array([ 297000., 1580000.,  562100., ...,  369950.,  300000.,  575950.])

In [ ]:
from sklearn.metrics import r2_score
print(r2_score(y_test,y_pred))

0.4735213014212426


# Multiple Linear Regression

In [ ]:
df.corr()

id  bedrooms  bathrooms  sqft_living  sqft_lot    floors  \
id             1.000000  0.001286   0.005160    -0.012258 -0.132109  0.018525   
bedrooms       0.001286  1.000000   0.515884     0.576671  0.031703  0.175429   
bathrooms      0.005160  0.515884   1.000000     0.754665  0.087740  0.500653   
sqft_living   -0.012258  0.576671   0.754665     1.000000  0.172826  0.353949   
sqft_lot      -0.132109  0.031703   0.087740     0.172826  1.000000 -0.005201   
floors         0.018525  0.175429   0.500653     0.353949 -0.005201  1.000000   
waterfront    -0.002721 -0.006582   0.063744     0.103818  0.021604  0.023698   
view           0.011592  0.079532   0.187737     0.284611  0.074710  0.029444   
condition     -0.023783  0.028472  -0.124982    -0.058753 -0.008958 -0.263768   
grade          0.008130  0.356967   0.664983     0.762704  0.113621  0.458183   
sqft_above    -0.010842  0.477600   0.685342     0.876597  0.183512  0.523885   
sqft_basement -0.005151  0.303093   0.283770     0.435043  0.015286 -0.245705   
yr_built       0.021380  0.154178   0.506019     0.318049  0.053080  0.489319   
yr_renovated  -0.016907  0.018841   0.050739     0.055363  0.007644  0.006338   
zipcode       -0.008224 -0.152668  -0.203866    -0.199430 -0.129574 -0.059121   
lat           -0.001891 -0.008931   0.024573     0.052529 -0.085683  0.049614   
long           0.020799  0.129473   0.223042     0.240223  0.229521  0.125419   
sqft_living15 -0.002901  0.391638   0.568634     0.756420  0.144608  0.279885   
sqft_lot15    -0.138798  0.029244   0.087175     0.183286  0.718557 -0.011269   
price         -0.016797  0.308338   0.525134     0.702044  0.089655  0.256786   

               waterfront      view  condition     grade  sqft_above  \
id              -0.002721  0.011592  -0.023783  0.008130   -0.010842   
bedrooms        -0.006582  0.079532   0.028472  0.356967    0.477600   
bathrooms        0.063744  0.187737  -0.124982  0.664983    0.685342   
sqft_living      0.103818  0.284611  -0.058753  0.762704    0.876597   
sqft_lot         0.021604  0.074710  -0.008958  0.113621    0.183512   
floors           0.023698  0.029444  -0.263768  0.458183    0.523885   
waterfront       1.000000  0.401857   0.016653  0.082775    0.072075   
view             0.401857  1.000000   0.045990  0.251321    0.167649   
condition        0.016653  0.045990   1.000000 -0.144674   -0.158214   
grade            0.082775  0.251321  -0.144674  1.000000    0.755923   
sqft_above       0.072075  0.167649  -0.158214  0.755923    1.000000   
sqft_basement    0.080588  0.276947   0.174105  0.168392   -0.051943   
yr_built        -0.026161 -0.053440  -0.361417  0.446963    0.423898   
yr_renovated     0.092885  0.103917  -0.060618  0.014414    0.023285   
zipcode          0.030285  0.084827   0.003026 -0.184862   -0.261190   
lat             -0.014274  0.006157  -0.014941  0.114084   -0.000816   
long            -0.041910 -0.078400  -0.106500  0.198372    0.343803   
sqft_living15    0.086463  0.280439  -0.092824  0.713202    0.731870   
sqft_lot15       0.030703  0.072575  -0.003406  0.119248    0.194050   
price            0.266331  0.397346   0.036392  0.667463    0.605566   

               sqft_basement  yr_built  yr_renovated   zipcode       lat  \
id                 -0.005151  0.021380     -0.016907 -0.008224 -0.001891   
bedrooms            0.303093  0.154178      0.018841 -0.152668 -0.008931   
bathrooms           0.283770  0.506019      0.050739 -0.203866  0.024573   
sqft_living         0.435043  0.318049      0.055363 -0.199430  0.052529   
sqft_lot            0.015286  0.053080      0.007644 -0.129574 -0.085683   
floors             -0.245705  0.489319      0.006338 -0.059121  0.049614   
waterfront          0.080588 -0.026161      0.092885  0.030285 -0.014274   
view                0.276947 -0.053440      0.103917  0.084827  0.006157   
condition           0.174105 -0.361417     -0.060618  0.003026 -0.014941   
grade               0.168392  0.446963      0.

In [ ]:
# d= df.drop(['sqft_living', 'sqft_lot15','sqft_basement','id', 'yr_built', 'yr_renovated', 'zipcode', 'waterfront', 'view', 'condition', 'lat', 'long'],axis=1)
# d
d= df.drop(['id','zipcode'],axis=1)
d

bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  view  \
0             3       1.00         1180      5650     1.0           0     0   
1             3       2.25         2570      7242     2.0           0     0   
2             2       1.00          770     10000     1.0           0     0   
3             4       3.00         1960      5000     1.0           0     0   
4             3       2.00         1680      8080     1.0           0     0   
...         ...        ...          ...       ...     ...         ...   ...   
21608         3       2.50         1530      1131     3.0           0     0   
21609         4       2.50         2310      5813     2.0           0     0   
21610         2       0.75         1020      1350     2.0           0     0   
21611         3       2.50         1600      2388     2.0           0     0   
21612         2       0.75         1020      1076     2.0           0     0   

       condition  grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
0              3      7        1180              0      1955             0   
1              3      7        2170            400      1951          1991   
2              3      6         770              0      1933             0   
3              5      7        1050            910      1965             0   
4              3      8        1680              0      1987             0   
...          ...    ...         ...            ...       ...           ...   
21608          3      8        1530              0      2009             0   
21609          3      8        2310              0      2014             0   
21610          3      7        1020              0      2009             0   
21611          3      8        1600              0      2004             0   
21612          3      7        1020              0      2008             0   

           lat     long  sqft_living15  sqft_lot15     price  
0      47.5112 -122.257           1340        5650  221900.0  
1      47.7210 -122.319           1690        7639  538000.0  
2      47.7379 -122.233           2720        8062  180000.0  
3      47.5208 -122.393           1360        5000  604000.0  
4      47.6168 -122.045           1800        7503  510000.0  
...        ...      ...            ...         ...       ...  
21608  47.6993 -122.346           1530        1509  360000.0  
21609  47.5107 -122.362           1830        7200  400000.0  
21610  47.5944 -122.299           1020        2007  402101.0  
21611  47.5345 -122.069           1410        1287  400000.0  
21612  47.5941 -122.299           1020        1357  325000.0  

[21613 rows x 18 columns]

In [ ]:
X= d.iloc[:,:-1].values
X

array([[ 3.0000e+00,  1.0000e+00,  1.1800e+03, ..., -1.2226e+02,
         1.3400e+03,  5.6500e+03],
       [ 3.0000e+00,  2.2500e+00,  2.5700e+03, ..., -1.2232e+02,
         1.6900e+03,  7.6390e+03],
       [ 2.0000e+00,  1.0000e+00,  7.7000e+02, ..., -1.2223e+02,
         2.7200e+03,  8.0620e+03],
       ...,
       [ 2.0000e+00,  7.5000e-01,  1.0200e+03, ..., -1.2230e+02,
         1.0200e+03,  2.0070e+03],
       [ 3.0000e+00,  2.5000e+00,  1.6000e+03, ..., -1.2207e+02,
         1.4100e+03,  1.2870e+03],
       [ 2.0000e+00,  7.5000e-01,  1.0200e+03, ..., -1.2230e+02,
         1.0200e+03,  1.3570e+03]])

In [ ]:
y= d.iloc[:,-1].values
y

array([221900., 538000., 180000., ..., 402101., 400000., 325000.])

# Splitting dataset into Train set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state=0)

In [ ]:
from sklearn.linear_model import LinearRegression
regressor= LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

# Predicting Test Set results

In [ ]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=4) #decimal number 4 tk when(precision=4)
np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1)

array([[ 380823.8246,  297000.    ],
       [1519888.367 , 1580000.    ],
       [ 528888.0661,  562100.    ],
       ...,
       [ 345297.3938,  369950.    ],
       [ 197342.8138,  300000.    ],
       [ 399948.7002,  575950.    ]])

In [ ]:
from sklearn.metrics import r2_score
print(r2_score(y_test,y_pred))

0.68895880595263


# Polynomial Regressor

In [ ]:
X= d.iloc[:,1:-1].values
X

array([[ 1.0000e+00,  1.1800e+03,  5.6500e+03, ..., -1.2226e+02,
         1.3400e+03,  5.6500e+03],
       [ 2.2500e+00,  2.5700e+03,  7.2420e+03, ..., -1.2232e+02,
         1.6900e+03,  7.6390e+03],
       [ 1.0000e+00,  7.7000e+02,  1.0000e+04, ..., -1.2223e+02,
         2.7200e+03,  8.0620e+03],
       ...,
       [ 7.5000e-01,  1.0200e+03,  1.3500e+03, ..., -1.2230e+02,
         1.0200e+03,  2.0070e+03],
       [ 2.5000e+00,  1.6000e+03,  2.3880e+03, ..., -1.2207e+02,
         1.4100e+03,  1.2870e+03],
       [ 7.5000e-01,  1.0200e+03,  1.0760e+03, ..., -1.2230e+02,
         1.0200e+03,  1.3570e+03]])

In [ ]:
y= d.iloc[:,-1].values
y

array([221900., 538000., 180000., ..., 402101., 400000., 325000.])

# Training Linear Regression Model

In [ ]:
from sklearn.linear_model import LinearRegression
lin_reg= LinearRegression()
lin_reg.fit(X,y)

LinearRegression()

# Training Polynomial Regression Model

In [ ]:
from sklearn.preprocessing import PolynomialFeatures
poly_reg= PolynomialFeatures(degree=2)
X_poly= poly_reg.fit_transform(X)

In [ ]:
X

array([[ 1.0000e+00,  1.1800e+03,  5.6500e+03, ..., -1.2226e+02,
         1.3400e+03,  5.6500e+03],
       [ 2.2500e+00,  2.5700e+03,  7.2420e+03, ..., -1.2232e+02,
         1.6900e+03,  7.6390e+03],
       [ 1.0000e+00,  7.7000e+02,  1.0000e+04, ..., -1.2223e+02,
         2.7200e+03,  8.0620e+03],
       ...,
       [ 7.5000e-01,  1.0200e+03,  1.3500e+03, ..., -1.2230e+02,
         1.0200e+03,  2.0070e+03],
       [ 2.5000e+00,  1.6000e+03,  2.3880e+03, ..., -1.2207e+02,
         1.4100e+03,  1.2870e+03],
       [ 7.5000e-01,  1.0200e+03,  1.0760e+03, ..., -1.2230e+02,
         1.0200e+03,  1.3570e+03]])

In [ ]:
X_poly

array([[1.0000e+00, 1.0000e+00, 1.1800e+03, ..., 1.7956e+06, 7.5710e+06,
        3.1922e+07],
       [1.0000e+00, 2.2500e+00, 2.5700e+03, ..., 2.8561e+06, 1.2910e+07,
        5.8354e+07],
       [1.0000e+00, 1.0000e+00, 7.7000e+02, ..., 7.3984e+06, 2.1929e+07,
        6.4996e+07],
       ...,
       [1.0000e+00, 7.5000e-01, 1.0200e+03, ..., 1.0404e+06, 2.0471e+06,
        4.0280e+06],
       [1.0000e+00, 2.5000e+00, 1.6000e+03, ..., 1.9881e+06, 1.8147e+06,
        1.6564e+06],
       [1.0000e+00, 7.5000e-01, 1.0200e+03, ..., 1.0404e+06, 1.3841e+06,
        1.8414e+06]])

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test= train_test_split(X_poly,y,test_size=0.2,random_state=0)

In [ ]:
lin_reg2= LinearRegression()
lin_reg2.fit(X_poly,y)

LinearRegression()

In [ ]:
lin_reg2.fit(X_train,y_train)

LinearRegression()

In [ ]:
y_pred= lin_reg2.predict(X_test)

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.7869694397918191

# SVR

In [ ]:
X

array([[ 3.0000e+00,  1.0000e+00,  1.1800e+03, ..., -1.2226e+02,
         1.3400e+03,  5.6500e+03],
       [ 3.0000e+00,  2.2500e+00,  2.5700e+03, ..., -1.2232e+02,
         1.6900e+03,  7.6390e+03],
       [ 2.0000e+00,  1.0000e+00,  7.7000e+02, ..., -1.2223e+02,
         2.7200e+03,  8.0620e+03],
       ...,
       [ 2.0000e+00,  7.5000e-01,  1.0200e+03, ..., -1.2230e+02,
         1.0200e+03,  2.0070e+03],
       [ 3.0000e+00,  2.5000e+00,  1.6000e+03, ..., -1.2207e+02,
         1.4100e+03,  1.2870e+03],
       [ 2.0000e+00,  7.5000e-01,  1.0200e+03, ..., -1.2230e+02,
         1.0200e+03,  1.3570e+03]])

In [ ]:
y

array([221900., 538000., 180000., ..., 402101., 400000., 325000.])

In [ ]:
X.shape

(21613, 16)

In [ ]:
y.shape

(21613,)

In [ ]:
y=y.reshape(len(y),1)

In [ ]:
y

array([[221900.],
       [538000.],
       [180000.],
       ...,
       [402101.],
       [400000.],
       [325000.]])

# Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()
X=sc_x.fit_transform(X)

sc_y=StandardScaler()
y=sc_y.fit_transform(y)

In [ ]:
X

array([[-1.4475, -0.9798, -0.2283, ..., -0.3061, -0.9434, -0.2607],
       [ 0.1756,  0.5336, -0.1899, ..., -0.7463, -0.4327, -0.1879],
       [-1.4475, -1.4263, -0.1233, ..., -0.1357,  1.0701, -0.1724],
       ...,
       [-1.7721, -1.154 , -0.3321, ..., -0.6043, -1.4103, -0.3941],
       [ 0.5002, -0.5225, -0.3071, ...,  1.0289, -0.8412, -0.4205],
       [-1.7721, -1.154 , -0.3388, ..., -0.6043, -1.4103, -0.4179]])

In [ ]:
y

array([[-0.8664],
       [-0.0059],
       [-0.9805],
       ...,
       [-0.3759],
       [-0.3816],
       [-0.5858]])

# Training SVR model on dataset

In [ ]:
from sklearn.svm import SVR
regressor=SVR(kernel='rbf')
regressor.fit(X,y)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

In [ ]:
X

array([[-1.4475, -0.9798, -0.2283, ..., -0.3061, -0.9434, -0.2607],
       [ 0.1756,  0.5336, -0.1899, ..., -0.7463, -0.4327, -0.1879],
       [-1.4475, -1.4263, -0.1233, ..., -0.1357,  1.0701, -0.1724],
       ...,
       [-1.7721, -1.154 , -0.3321, ..., -0.6043, -1.4103, -0.3941],
       [ 0.5002, -0.5225, -0.3071, ...,  1.0289, -0.8412, -0.4205],
       [-1.7721, -1.154 , -0.3388, ..., -0.6043, -1.4103, -0.4179]])

In [ ]:
y

array([[-0.8664],
       [-0.0059],
       [-0.9805],
       ...,
       [-0.3759],
       [-0.3816],
       [-0.5858]])

In [ ]:
y_pred=regressor.predict(X)
y_pred

array([-0.6924,  0.1658, -0.4278, ..., -0.605 , -0.2923, -0.6106])

In [ ]:
y_test=sc_y.inverse_transform(y)
y_test

array([[221900.],
       [538000.],
       [180000.],
       ...,
       [402101.],
       [400000.],
       [325000.]])

In [ ]:
from sklearn.metrics import r2_score
r2_score(y,y_pred)

0.8128822465034027

# Decision Tree Regressor

In [ ]:
X= d.iloc[:,:-1].values
X

array([[ 3.0000e+00,  1.0000e+00,  1.1800e+03, ..., -1.2226e+02,
         1.3400e+03,  5.6500e+03],
       [ 3.0000e+00,  2.2500e+00,  2.5700e+03, ..., -1.2232e+02,
         1.6900e+03,  7.6390e+03],
       [ 2.0000e+00,  1.0000e+00,  7.7000e+02, ..., -1.2223e+02,
         2.7200e+03,  8.0620e+03],
       ...,
       [ 2.0000e+00,  7.5000e-01,  1.0200e+03, ..., -1.2230e+02,
         1.0200e+03,  2.0070e+03],
       [ 3.0000e+00,  2.5000e+00,  1.6000e+03, ..., -1.2207e+02,
         1.4100e+03,  1.2870e+03],
       [ 2.0000e+00,  7.5000e-01,  1.0200e+03, ..., -1.2230e+02,
         1.0200e+03,  1.3570e+03]])

In [ ]:
y=  d.iloc[:,-1].values
y

array([221900., 538000., 180000., ..., 402101., 400000., 325000.])

#Training Decision Tree Model

In [ ]:
from sklearn.tree import DecisionTreeRegressor
regressor= DecisionTreeRegressor(random_state=0)
regressor.fit(X,y)

DecisionTreeRegressor(random_state=0)

In [ ]:
from sklearn.metrics import r2_score
r2_score(y,regressor.predict(X))

0.9991345917455311

#Random Forest Regressor

In [ ]:
X= d.iloc[:,1:-1].values
X

array([[ 1.0000e+00,  1.1800e+03,  5.6500e+03, ..., -1.2226e+02,
         1.3400e+03,  5.6500e+03],
       [ 2.2500e+00,  2.5700e+03,  7.2420e+03, ..., -1.2232e+02,
         1.6900e+03,  7.6390e+03],
       [ 1.0000e+00,  7.7000e+02,  1.0000e+04, ..., -1.2223e+02,
         2.7200e+03,  8.0620e+03],
       ...,
       [ 7.5000e-01,  1.0200e+03,  1.3500e+03, ..., -1.2230e+02,
         1.0200e+03,  2.0070e+03],
       [ 2.5000e+00,  1.6000e+03,  2.3880e+03, ..., -1.2207e+02,
         1.4100e+03,  1.2870e+03],
       [ 7.5000e-01,  1.0200e+03,  1.0760e+03, ..., -1.2230e+02,
         1.0200e+03,  1.3570e+03]])

In [ ]:
y= d.iloc[:,-1].values
y

array([221900., 538000., 180000., ..., 402101., 400000., 325000.])

##Training Random Forest model

In [ ]:
from sklearn.ensemble import RandomForestRegressor
regressor= RandomForestRegressor(n_estimators=10, random_state=0)
regressor.fit(X,y)

RandomForestRegressor(n_estimators=10, random_state=0)

In [ ]:
from sklearn.metrics import r2_score
r2_score(y,regressor.predict(X))

0.9739614821985265

In [7]:
accuracy= {
    "Linear Regression": 0.4735213014212426,
    "Polynomial Regression":  0.7869694397918191,
    "SVR": 0.8128822465034027,
    "Decision Tree Regressor": 0.9991345917455311,
    "Random Forest Regressor": 0.9739614821985265
    }

In [9]:
Series = pd.Series(accuracy)
Series

Linear Regression          0.473521
Polynomial Regression      0.786969
SVR                        0.812882
Decision Tree Regressor    0.999135
Random Forest Regressor    0.973961
dtype: float64